[package]
name = "hdl_compiler"
version = "0.1.0"
authors = ["maxkl <max@maxkl.de>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
matches = "0.1.8"
serde = { version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
clap = "2.33.0"

[[bin]]
name = "hdlc"
path = "src/main.rs"
